---
abstract: 'ASCII85 encode/decode data and print to standard output'
author:
  - 'Timothe Litt <tlhackque@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Basename: 0
  File::Spec: 0
  Module::Signature: 0
  Socket: 0
  Test::Files: 0
  Test::More: 0.94
  perl: 5.008008
configure_requires:
  ExtUtils::MakeMaker: 0
  perl: 5.008008
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: base85
provides: {}
requires:
  Convert::Ascii85: 0
  Getopt::Long: 0
  Pod::Usage: 0
  perl: 5.008008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/tlhackque/base85/issues
  repository: https://github.com/tlhackque/base85.git
version: 1.0
x_Dist_Zilla:
  perl:
    version: 5.008008
  plugins:
    -
      class: Dist::Zilla::Plugin::Run::BeforeBuild
      config:
        Dist::Zilla::Plugin::Run::Role::Runner:
          fatal_errors: 1
          quiet: 0
          run:
            - "echo \"Commit log for %n, most recent first\" >Commitlog"
            - "echo \"\" >>Commitlog"
            - "git log --format=\"- %%s%%n\" >>Commitlog"
      name: Run::BeforeBuild
      version: 0.043
    -
      class: Dist::Zilla::Plugin::Encoding
      name: Encoding
      version: 5.043
    -
      class: Dist::Zilla::Plugin::VersionFromModule
      name: VersionFromModule
      version: 0.08
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: CopyFilesFromBuild
      version: 0.151680
    -
      class: Dist::Zilla::Plugin::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename:
            - MANIFEST
            - META.json
            - META.yml
            - Makefile.PL
          exclude_match:
            - '\#.*\#$'
            - '\.bak$'
            - '\.tmp$'
            - '~$'
          follow_symlinks: 0
          include_dotfiles: 0
          prefix: ''
          prune_directory: []
          root: '.'
      name: GatherDir
      version: 5.043
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: PruneCruft
      version: 5.043
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 5.043
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: MetaProvides::Package/AUTOVIV/:InstallModulesPM
              version: 5.043
        Dist::Zilla::Role::MetaProvider::Provider:
          Dist::Zilla::Role::MetaProvider::Provider::VERSION: 2.001010
          inherit_missing: 1
          inherit_version: 1
          meta_noindex: 1
      name: MetaProvides::Package
      version: 2.003001
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 5.043
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: MinimumPerl
      version: 1.006
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: MetaYAML
      version: 5.043
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 5.043
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: ExtraTests
      version: 5.043
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: ExecDir
      version: 5.043
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: ShareDir
      version: 5.043
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: MakeMaker
      version: 5.043
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 5.043
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: Test::ReportPrereqs
      version: 0.021
    -
      class: Dist::Zilla::Plugin::Manifest
      name: Manifest
      version: 5.043
    -
      class: Dist::Zilla::Plugin::Signature
      name: Signature
      version: 1.100930
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: 5.043
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: 5.043
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: 5.043
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.043
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.043
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.043
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: 5.043
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.043
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: 5.043
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.043
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.043
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: 5.043
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: 5.043
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: MetaProvides::Package/AUTOVIV/:InstallModulesPM
      version: 5.043
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.043
